# Generated by Django 2.2.6 on 2019-11-06 05:56

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(db_column='Cargo', max_length=50)),
                ('desc_cargo', models.CharField(db_column='Descripcion', max_length=60)),
            ],
            options={
                'db_table': 'cargos',
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(db_column='Nombre_Carrera', max_length=90)),
            ],
            options={
                'db_table': 'carreras',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(blank=True, db_column='Codigo_Curso', max_length=10, null=True)),
                ('nombre_curso', models.CharField(db_column='Nombre_Curso', max_length=30)),
                ('descripcion_curso', models.CharField(blank=True, db_column='Descripcion_Curso', max_length=50, null=True)),
                ('horario_curso', models.TimeField(db_column='Horario_Curso')),
                ('periodos_diarios', models.IntegerField(blank=True, db_column='Periodos_Diarios', null=True)),
                ('periodos_semanales', models.IntegerField(blank=True, db_column='Periodos_Semanales', null=True)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_codigo', models.CharField(db_column='Codigo', max_length=15)),
                ('estudiante_nombres', models.CharField(db_column='Estudiante_Nombres', max_length=50)),
                ('estudiante_apellidos', models.CharField(db_column='Estudiante_Apellidos', max_length=50)),
                ('fecha_nacimiento', models.DateField(db_column='Fecha_Nacimiento')),
                ('direccion', models.CharField(db_column='Direccion', max_length=100)),
                ('no_celular', models.CharField(blank=True, db_column='No_Celular', max_length=8, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('SG', 'Seleccione genero del Estudiante'), ('M', 'Masculino'), ('F', 'Femenino')], default='SG', max_length=2)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Inscripcion')),
                ('mensualidad', models.FloatField(db_column='Mensualidad')),
            ],
            options={
                'db_table': 'estudiantes',
                'ordering': ['estudiante_apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grado', models.CharField(db_column='Nombre_Grado', max_length=20)),
                ('seccion_grado', models.CharField(db_column='Seccion_Grado', max_length=3)),
            ],
            options={
                'db_table': 'grados',
            },
        ),
        migrations.CreateModel(
            name='MesesColegiatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mes', models.CharField(db_column='Nombre_Mes', max_length=12)),
            ],
            options={
                'db_table': 'meses_colegiaturas',
            },
        ),
        migrations.CreateModel(
            name='NivelesEducativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(db_column='Nombre_Nivel', max_length=25)),
            ],
            options={
                'db_table': 'niveles_educativos',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_nombres', models.CharField(db_column='Personal_Nombres', max_length=45)),
                ('personal_apellidos', models.CharField(db_column='Personal_Apellidos', max_length=45)),
                ('celular', models.CharField(db_column='Celular', max_length=12)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Creacion')),
                ('salario', models.FloatField(blank=True, db_column='Salario', null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Cargos')),
            ],
            options={
                'db_table': 'personal',
                'ordering': ['personal_apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi_tutor', models.CharField(db_column='DPI_Tutor', max_length=14)),
                ('nombres_tutor', models.CharField(db_column='Nombres_Tutor', max_length=50)),
                ('apellidos_tutor', models.CharField(db_column='Apellidos_Tutor', max_length=50)),
                ('telefono_tutor', models.CharField(blank=True, db_column='Telefono_Tutor', max_length=8, null=True)),
                ('direccion_tutor', models.CharField(blank=True, db_column='Direccion_Tutor', max_length=100, null=True)),
                ('email_tutor', models.CharField(blank=True, db_column='email_Tutor', max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Inscripcion')),
            ],
            options={
                'db_table': 'tutores',
                'ordering': ['apellidos_tutor'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='correo electrónico')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Cargos')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Transacestudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True, db_column='Fecha_Transaccion')),
                ('cantidadtotal', models.FloatField(db_column='CantidadTotal')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
                ('colegiaturas_id_mes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.MesesColegiatura')),
                ('estudiantes_id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Estudiantes')),
                ('personal_id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Personal')),
                ('tutores_id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Tutores')),
            ],
            options={
                'db_table': 'transac_estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_parcial', models.FloatField(db_column='Primer_Parcial', default=0)),
                ('segundo_parcial', models.FloatField(db_column='Segundo_Parcial', default=0)),
                ('tercer_parcial', models.FloatField(db_column='Tercer_Parcial', default=0)),
                ('cuarto_parcial', models.FloatField(db_column='Cuarto_Parcial', default=0)),
                ('quinto_parcial', models.FloatField(db_column='Quinto_Parcial', default=0)),
                ('nota_final', models.FloatField(db_column='Nota_Final', default=0)),
                ('cursos_id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Cursos')),
                ('estudiantes_id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Estudiantes')),
            ],
            options={
                'db_table': 'notas',
            },
        ),
        migrations.CreateModel(
            name='GradosCursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos_id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Cursos')),
                ('grados_id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Grados')),
            ],
            options={
                'db_table': 'grados_cursos',
            },
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='tutores_id_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Tutores'),
        ),
        migrations.CreateModel(
            name='EstudianteCuros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos_id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Cursos')),
                ('estudiantes_id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Estudiantes')),
            ],
            options={
                'db_table': 'estudiante_curso',
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='personal_id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Personal'),
        ),
        migrations.CreateModel(
            name='CarrerasGrados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carreras_id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Carreras')),
                ('grados_id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Grados')),
            ],
            options={
                'db_table': 'carreras_grados',
            },
        ),
        migrations.AddField(
            model_name='carreras',
            name='nivele_educativo_id_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.NivelesEducativos'),
        ),
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_column='User', max_length=15)),
                ('password', models.CharField(db_column='Password', max_length=25)),
                ('personal_id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JuanDiegoSys.Personal')),
            ],
            options={
                'db_table': 'accesos',
            },
        ),
    ]
