# Generated by Django 2.2.6 on 2019-11-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JuanDiegoSys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
    ]
